package sudoku;

import java.io.IOException;

public class SudokuSolverApp {
	public static final boolean DEBUG = true;

	public static void main(String[] args) throws IOException, InterruptedException {
		String dataFile = "data/sudoku.txt";
		String yicesCommand = "yices";
		String autoGeneratedYicesFile = "modules/sudoku.ys";
		
		AbstractSudokuSolver solver = new ConcreteSudokuSolver(dataFile, yicesCommand, autoGeneratedYicesFile);
		solver.solve();
	}
}
